# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: QLever Documentation

# Navigation on the left side
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Benchmarks: benchmarks.md
  - Compliance: compliance.md
  - FAQ: faq.md
  # - Getting started:
  #   - qlever-control: qlever-control.md
  - Reference:
    - Qleverfile settings: qleverfile.md
    # - Datasets: qlever-control/datasets.md

repo_url: https://github.com/qlever-dev/qlever-docs
edit_uri: edit/master/docs
site_description: Documentation for the QLever graph database
site_author: The QLever authors
copyright: >
  Copyright &copy; 2025 The QLever authors
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.ico
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
  features:
    - navigation.tracking
    # Sections
    - navigation.sections
    - navigation.expand
    # Not compatible with toc.integrate
    #- navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - privacy
  # Note on Cookies and Github: https://github.com/squidfunk/mkdocs-material/discussions/4666
  - search
  - social
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors
# or https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-authors
# https://squidfunk.github.io/mkdocs-material/reference/

extra:
  version:
    provider: mike
  social:
    # Note: the icons are the path in site-packages/material/templates/.icons/...
    - icon: material/github
      link: https://github.com/ad-freiburg
    - icon: material/language-python
      link: https://pypi.org/project/qlever
    - icon: material/web
      link: https://ad.informatik.uni-freiburg.de

markdown_extensions:
    # Captions for many types of blocks
    - pymdownx.blocks.caption
    # Emojis with :name:
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: ad-freiburg
        repo: qlever
        normalize_issue_symbols: true
    # Syntax highlighting
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences
    # Convert some symbols to unicode (e.g. (c) to ©)
    - pymdownx.smartsymbols
    # Tabs in a document
    - pymdownx.tabbed:
        alternate_style: true
    # Collapsible callouts
    - admonition
    - pymdownx.details
    - attr_list
    - footnotes
    - md_in_html
